/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedArenaRouteImport } from './routes/_authenticated/arena'
import { Route as AuthenticatedCardArtRouteImport } from './routes/_authenticated/card-art'
import { Route as AuthenticatedCrimesRouteImport } from './routes/_authenticated/crimes'
import { Route as AuthenticatedDeckRouteImport } from './routes/_authenticated/deck'
import { Route as AuthenticatedGymRouteImport } from './routes/_authenticated/gym'
import { Route as AuthenticatedHospitalRouteImport } from './routes/_authenticated/hospital'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedTavernRouteImport } from './routes/_authenticated/tavern'
import { Route as AuthenticatedBattleBattleIdRouteImport } from './routes/_authenticated/battle.$battleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArenaRoute = AuthenticatedArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardArtRoute = AuthenticatedCardArtRouteImport.update({
  id: '/card-art',
  path: '/card-art',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrimesRoute = AuthenticatedCrimesRouteImport.update({
  id: '/crimes',
  path: '/crimes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeckRoute = AuthenticatedDeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGymRoute = AuthenticatedGymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHospitalRoute = AuthenticatedHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTavernRoute = AuthenticatedTavernRouteImport.update({
  id: '/tavern',
  path: '/tavern',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBattleBattleIdRoute =
  AuthenticatedBattleBattleIdRouteImport.update({
    id: '/battle/$battleId',
    path: '/battle/$battleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/card-art': typeof AuthenticatedCardArtRoute
  '/crimes': typeof AuthenticatedCrimesRoute
  '/deck': typeof AuthenticatedDeckRoute
  '/gym': typeof AuthenticatedGymRoute
  '/hospital': typeof AuthenticatedHospitalRoute
  '/shop': typeof AuthenticatedShopRoute
  '/tavern': typeof AuthenticatedTavernRoute
  '/battle/$battleId': typeof AuthenticatedBattleBattleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/card-art': typeof AuthenticatedCardArtRoute
  '/crimes': typeof AuthenticatedCrimesRoute
  '/deck': typeof AuthenticatedDeckRoute
  '/gym': typeof AuthenticatedGymRoute
  '/hospital': typeof AuthenticatedHospitalRoute
  '/shop': typeof AuthenticatedShopRoute
  '/tavern': typeof AuthenticatedTavernRoute
  '/battle/$battleId': typeof AuthenticatedBattleBattleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/arena': typeof AuthenticatedArenaRoute
  '/_authenticated/card-art': typeof AuthenticatedCardArtRoute
  '/_authenticated/crimes': typeof AuthenticatedCrimesRoute
  '/_authenticated/deck': typeof AuthenticatedDeckRoute
  '/_authenticated/gym': typeof AuthenticatedGymRoute
  '/_authenticated/hospital': typeof AuthenticatedHospitalRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/tavern': typeof AuthenticatedTavernRoute
  '/_authenticated/battle/$battleId': typeof AuthenticatedBattleBattleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/arena'
    | '/card-art'
    | '/crimes'
    | '/deck'
    | '/gym'
    | '/hospital'
    | '/shop'
    | '/tavern'
    | '/battle/$battleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/arena'
    | '/card-art'
    | '/crimes'
    | '/deck'
    | '/gym'
    | '/hospital'
    | '/shop'
    | '/tavern'
    | '/battle/$battleId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/arena'
    | '/_authenticated/card-art'
    | '/_authenticated/crimes'
    | '/_authenticated/deck'
    | '/_authenticated/gym'
    | '/_authenticated/hospital'
    | '/_authenticated/shop'
    | '/_authenticated/tavern'
    | '/_authenticated/battle/$battleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/arena': {
      id: '/_authenticated/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof AuthenticatedArenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/card-art': {
      id: '/_authenticated/card-art'
      path: '/card-art'
      fullPath: '/card-art'
      preLoaderRoute: typeof AuthenticatedCardArtRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crimes': {
      id: '/_authenticated/crimes'
      path: '/crimes'
      fullPath: '/crimes'
      preLoaderRoute: typeof AuthenticatedCrimesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deck': {
      id: '/_authenticated/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof AuthenticatedDeckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gym': {
      id: '/_authenticated/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof AuthenticatedGymRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospital': {
      id: '/_authenticated/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof AuthenticatedHospitalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tavern': {
      id: '/_authenticated/tavern'
      path: '/tavern'
      fullPath: '/tavern'
      preLoaderRoute: typeof AuthenticatedTavernRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle/$battleId': {
      id: '/_authenticated/battle/$battleId'
      path: '/battle/$battleId'
      fullPath: '/battle/$battleId'
      preLoaderRoute: typeof AuthenticatedBattleBattleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArenaRoute: typeof AuthenticatedArenaRoute
  AuthenticatedCardArtRoute: typeof AuthenticatedCardArtRoute
  AuthenticatedCrimesRoute: typeof AuthenticatedCrimesRoute
  AuthenticatedDeckRoute: typeof AuthenticatedDeckRoute
  AuthenticatedGymRoute: typeof AuthenticatedGymRoute
  AuthenticatedHospitalRoute: typeof AuthenticatedHospitalRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedTavernRoute: typeof AuthenticatedTavernRoute
  AuthenticatedBattleBattleIdRoute: typeof AuthenticatedBattleBattleIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArenaRoute: AuthenticatedArenaRoute,
  AuthenticatedCardArtRoute: AuthenticatedCardArtRoute,
  AuthenticatedCrimesRoute: AuthenticatedCrimesRoute,
  AuthenticatedDeckRoute: AuthenticatedDeckRoute,
  AuthenticatedGymRoute: AuthenticatedGymRoute,
  AuthenticatedHospitalRoute: AuthenticatedHospitalRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedTavernRoute: AuthenticatedTavernRoute,
  AuthenticatedBattleBattleIdRoute: AuthenticatedBattleBattleIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
